# 题库设置 [POST /exercise/setting]

|参数|必选|类型|参数说明|
|---|---|---|---|
|token|Y|String|用户ID|
|identity|Y|Integer|0: 免费, 1: VIP|
|type|Y|Integer|0: 科目一, 1: 科目四, 2: 恢复驾照, 3: 资格证|
|subType|Y|Integer|0: 小车, 1: 货车, 2: 客车, 3: 摩托车, 4: 危险品, 5: 出租车, 6: 教练员|

+ Request (application/json)
  {
    "token": "qwkdpqwkdpjoj12312-0",
    "identity": 0,
    "type": 0,
    "subType": 3
  }

+ Response 200 (application/json)
  {
      "c": 0,
      "m": "",
      "d": {

      }
  }

# 习题类型列表 [GET /exercise/type]

|参数|必选|类型|参数说明|
|---|---|---|---|
|token|Y|String|用户ID|
|参数|必选|类型|参数说明|

+ Parameters
  + token:"qwkdpqwkdpjoj12312-0" (required,String) - 用户ID

+ Response 200 (application/json)
  {
      "c": 0,
      "m": "",
      "d": {
        "types": [
          {
            "id": 1029,
            "name": "专项练习一"
          },{
            "id": 1031,
            "name": "专项练习二"
          },{
            "id": 1041,
            "name": "专项练习三"
          },{
            "id": 1055,
            "name": "专项练习四"
          },
        ]
      }
  }

# 章节列表 [POST /exercise/section]

|参数|必选|类型|参数说明|
|---|---|---|---|
|token|Y|String|用户ID|

+ Request (application/json)
  {
    "token": "qwkdpqwkdpjoj12312-0",
    "type": 1029
  }

+ Response 200 (application/json)
  {
      "c": 0,
      "m": "",
      "d": {
        "chapters": [
          {
            "id": 1029,
            "name": "专项练习一"
          },{
            "id": 1031,
            "name": "专项练习二"
          },{
            "id": 1041,
            "name": "专项练习三"
          },{
            "id": 1055,
            "name": "专项练习四"
          },
        ]
      }
  }

# 习题列表 [POST /exercise/list]

|参数|必选|类型|参数说明|
|---|---|---|---|
|token|Y|String|用户ID|
|section|Y|Integer|章节ID|

+ Request (application/json)
  {
    "token": "qwkdpqwkdpjoj12312-0",
    "section": [1031, 1021],
  }

+ Response 200 (application/json)
  {
      "c": 0,
      "m": "",
      "d": {
        "total": 1311, //题目总数
        "exercises": [
          {
            "id": 1029,
            "type": 0, //0:单选 1:多选 2:判断
            "title": "驾驶机动车在道路上范围交通安全法的行为, 属于什么行为?"
            "image": ["http://aaa.jpg", "http://aaa.jpg"]
            "video": ["http://aaa.mp4", "http://aaa.mp4"]
            "explain": "醉酒驾驶, 有公安机关约束至酒醒. 吊销机动车驾驶证, 已发追究刑事责任, 5年内不得重新取得驾驶证.", //文字讲解
            "audioExplain": "http://aaa.mp3", //语音讲解
            "videoExplain": "http://aaa.mp4", //语音讲解
            "answers": [
              {
                "option": 0, //答案选项 0：A 1：B 2：C 3：D
                "right": true, //是否正确答案
                "text": "违章行为", //文本答案内容
                "image": "http://aaa.jpg" //图片答案内容
              },{
                "option": 1,
                "right": false,
                "text": "违法行为",
                "image": "http://aaa.jpg"
              },{
                "option": 2,
                "right": false,
                "text": "过失行为",
                "image": "http://aaa.jpg"
              },{
                "option": 3,
                "right": false,
                "text": "违规行为",
                "image": "http://aaa.jpg"
              }
            ]
          },{
            "id": 1029,
            "type": 2, //0:单选 1:多选 2:判断
            "title": "驾驶机动车在道路上范围交通安全法的行为, 属于什么行为?"
            "image": ["http://aaa.jpg", "http://aaa.jpg"]
            "video": ["http://aaa.mp4", "http://aaa.mp4"]
            "explain": "醉酒驾驶, 有公安机关约束至酒醒. 吊销机动车驾驶证, 已发追究刑事责任, 5年内不得重新取得驾驶证.", //文字讲解
            "audioExplain": "http://aaa.mp3", //语音讲解
            "videoExplain": "http://aaa.mp4", //语音讲解
            "answers": [
              {
                "right": true //是否正确答案
                "text": "违章行为" //文本答案内容
                "image": "http://aaa.jpg" //图片答案内容
              },{
                "right": false
                "text": "违法行为"
                "image": "http://aaa.jpg"
              }
            ]
          }
        ]
      }
  }

# 提交答题结果 [POST /exercise/submit]

|参数|必选|类型|参数说明|
|---|---|---|---|
|token|Y|String|用户ID|
|result|Y|object[]|答题结果集合|

+ Request (application/json)
  {
    "token": "qwkdpqwkdpjoj12312-0",
    "result": [
      {
        "id": 1861, //题目ID
        "result": true //答题结果
      },{
        "id": 1231,
        "result": true
      },
    ]
  }

+ Response 200 (application/json)
  {
      "c": 0,
      "m": "",
      "d": {

      }
  }
