# 登录 [POST /user/login]

|参数|必选|类型|参数说明|
|---|---|---|---|
|us|是|String|登录名|
|ps|是|String|密码|

+ Request (application/json)
  {
    "us": "18618416321",
    "ps": "1234567"
  }

+ Response 200 (application/json)
  {
    "c": 0,
    "m": ""
    "d": {
      "username": "用户142918", //登录账号
      "name": "文东", //真实姓名
      "tel": "18618416321",
      "gender": 0 //0: 男, 1: 女
      "role": 0 //0: 免费, 1: VIP
      "vipinfo": {
          "subject": 0 //科目
          "models": 1 //车型
      }
    }
  }
