FORMAT: 1A
HOST: http://0.0.0.0

# 接口文档

推荐使用chrome插件[postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop),进行HTTP请求调试

# Group 首页
<!-- include(api-home.apib) -->

# Group 课程相关
<!-- include(api-lesson.apib) -->

# Group 未读相关
<!-- include(api-unread.apib) -->
