>postman数据：https://www.getpostman.com/collections/6aa64d7695c51232510f

# 服务者登陆 [POST /enterprise/account/login]
服务者登陆接口

请求字段说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|account|String|Y|手机号或邮箱地址|
|password|String|Y|密码|
|imei|String|Y|手机imei号|
|type|int|Y|客户端类型，0:安卓，1:ios|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
  {
    "account"     :   "test@cim120.com.cn",
    "password"    :   "123456",
    "imei"        :   "123456789",
    "type"        :   1
  }

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
      "user": {
        "companyGroup": 6,
        "companyId": 6,
        "companyName": "希盟医院",
        "email": "test@cim120.com.cn",
        "face": "http://files-test.cim120.cn/hmp/p/f/500023/6108575f078c7dc20b8d804041fe11d2cfa1fd47_small.jpg",
        "id": 500023,
        "name": "希盟疗养院",
        "phone": ""
      },
      "token": "3c29dc731852440295f8352d765960d4"
    },
    "success": true
  }

# 用户登出 [GET /enterprise/account/logout/{token}/{companyId}]

客户端调用接口退出登录，清除token


返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|

  + Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
      + companyId:6(required,String) - 当前accountId下的profileId
  + Request (application/json)

  + Response 200 (application/json)
    {
        "success":true,
        "code":1,
        "data":{
        }
    }


# 服务者编辑名称 [POST /enterprise/account/save]

修改服务者名称

请求字段说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|Y|帐号token|
|name|String|Y|帐号名称|
|companyId|int|Y|帐号名称|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
  {
    "token"    :   "ba138441223b4a04aefaa4a6ef27f308",
    "name"     :   "希盟疗养院",
    "companyId":6
  }

+ Response 200 (application/json)
  {
      "success":true,
      "code":1,
      "data":{
      }
  }


# 服务者头像图片上传 [POST /enterprise/portrait]

修改服务者名称

参数说明:
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|APP必须有/PC不需要|用户登录token|
|file|MultipartFile|Y|需要上传的图片|
|companyId|Long|Y|机构id|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
+ Response 200 (application/json)
  {
      "code": 1,
      "data": {
          "url": "http://files-test.cim120.cn/hmp/p/f/500023/5a9ba414ee90e0e2ad29c83843e5563b20547e36.jpg"
      },
      "success": true
  }

# 服务者修改密码 [POST /enterprise/account/password]

修改服务者名称

请求字段说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|Y|帐号token|
|oldPassword|String|Y|密码|
|password|String|Y|密码|
|companyId|Long|Y|机构id|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
  {
    "token"          :   "259dc602e3e14f82ad143855ad4a47b3",
    "oldPassword"    :   "654321",
    "password"       :   "123456",
    "companyId"      :   6
  }

+ Response 200 (application/json)
  {
      "success":true,
      "code":1,
      "data":{
      }
  }


# 服务者详情 [GET /enterprise/account/detail/{token}/{companyId}]

根据服务者token查询服务者详情


返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|

+ Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
      + companyId:6(required,String) - 当前accountId下的profileId
+ Request (application/json)

+ Response 200 (application/json)
    {
       "success":true,
       "code":1,
       "data":{
          "user":{
                "id" : 200048,
                "companyId" : 1,
                "companyName" : "郑大一",
                "name" : "小李",
                "face" : "http:\/\/image.cimyun.com\/face\/8aadcfc7ae25ef8d688bd197fec8acac",
                "phone" : 13812345678,
                "email" : "email@163.com",
                "companyGroup" : 1
                }
        }
    }

# 数据同步 [GET /enterprise/dataSync/{token}/{companyGroup}/{companyId}]

通过接口同步数据字典数据


参数说明：
|Field | 说明 |
| -- | -- |
| token | 用户token |
|companyGroup|机构组id|
|companyId|机构id|

+ Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
      + companyGroup:6(required,String) - companyGroup
      + companyId:6(required,String) - 当前accountId下的profileId
+ Request (application/json)

+ Response 200 (application/json)
    {
        "code": 1,
        "data": {
            "companies": [
                {
                    "id": 6,
                    "name": "希盟医院"
                },
                {
                    "id": 1292,
                    "name": "希盟医院222"
                }
            ],
            "download_pdf": "http://hmp.dev.cim120.cn/user/diagnose/healthguidance/pdf/download?taskId=",
            "export_pdf": "http://hmp.dev.cim120.cn/user/diagnose/healthguidance/pdf/export?taskId=",
            "diseaseTypes": [
                {
                    "examineTypeList": [
                        {
                            "id": 1,
                            "name": "尿常规化验"
                        },
                        {
                            "id": 2,
                            "name": "血液血红蛋白化验"
                        },
                        {
                            "id": 3,
                            "name": "血钾化验"
                        },
                        {
                            "id": 4,
                            "name": "血肌酐化验"
                        },
                        {
                            "id": 5,
                            "name": "尿酸化验"
                        },
                        {
                            "id": 6,
                            "name": "血脂化验"
                        },
                        {
                            "id": 7,
                            "name": "血糖化验"
                        },
                        {
                            "id": 8,
                            "name": "心电图报告"
                        },
                        {
                            "id": 9,
                            "name": "眼底检查"
                        },
                        {
                            "id": 10,
                            "name": "肾动脉彩超"
                        },
                        {
                            "id": 11,
                            "name": "颈动脉彩超"
                        },
                        {
                            "id": 12,
                            "name": "心彩超"
                        },
                        {
                            "id": 13,
                            "name": "肾彩超"
                        },
                        {
                            "id": 14,
                            "name": "醛固酮立卧位实验"
                        },
                        {
                            "id": 15,
                            "name": "尿素氮检查"
                        }
                    ],
                    "id": 1,
                    "name": "高血压"
                },
                {
                    "examineTypeList": [
                        {
                            "id": 7,
                            "name": "血糖化验"
                        },
                        {
                            "id": 9,
                            "name": "眼底检查"
                        },
                        {
                            "id": 16,
                            "name": "糖尿病足足背动脉检查"
                        },
                        {
                            "id": 17,
                            "name": "低密度脂蛋白胆固醇化验"
                        },
                        {
                            "id": 18,
                            "name": "甘油三酯化验"
                        },
                        {
                            "id": 19,
                            "name": "高密度脂蛋白胆固醇化验"
                        },
                        {
                            "id": 20,
                            "name": "尿常规"
                        },
                        {
                            "id": 21,
                            "name": "肝功能"
                        },
                        {
                            "id": 22,
                            "name": "肾功能"
                        },
                        {
                            "id": 23,
                            "name": "血清TSH"
                        },
                        {
                            "id": 24,
                            "name": "心电图"
                        },
                        {
                            "id": 25,
                            "name": "感觉神经检查"
                        },
                        {
                            "id": 26,
                            "name": "运动神经检查"
                        },
                        {
                            "id": 27,
                            "name": "自主神经检查"
                        },
                        {
                            "id": 28,
                            "name": "神经根检查"
                        },
                        {
                            "id": 29,
                            "name": "近段运动神经检查"
                        },
                        {
                            "id": 30,
                            "name": "颅神经检查"
                        },
                        {
                            "id": 31,
                            "name": "单神经病变检查"
                        },
                        {
                            "id": 32,
                            "name": "尿白蛋白检查"
                        },
                        {
                            "id": 33,
                            "name": "同步胰岛功能检查"
                        },
                        {
                            "id": 34,
                            "name": "胰岛素抗体检查"
                        },
                        {
                            "id": 35,
                            "name": "尿ACR"
                        },
                        {
                            "id": 36,
                            "name": "甲状腺抗体检查"
                        }
                    ],
                    "id": 2,
                    "name": "糖尿病"
                },
                {
                    "examineTypeList": [
                        {
                            "id": 37,
                            "name": "胸部X线检查"
                        },
                        {
                            "id": 38,
                            "name": "血气检查"
                        },
                        {
                            "id": 39,
                            "name": "呼吸衰竭检查"
                        },
                        {
                            "id": 40,
                            "name": "脉氧监测"
                        },
                        {
                            "id": 41,
                            "name": "O2检测"
                        },
                        {
                            "id": 42,
                            "name": "CO2检测"
                        },
                        {
                            "id": 43,
                            "name": "感染免疫监测"
                        },
                        {
                            "id": 44,
                            "name": "并发症监测"
                        },
                        {
                            "id": 45,
                            "name": "血常规"
                        },
                        {
                            "id": 46,
                            "name": "痰培养"
                        },
                        {
                            "id": 47,
                            "name": "G实验"
                        },
                        {
                            "id": 48,
                            "name": "GM实验"
                        },
                        {
                            "id": 49,
                            "name": "哮喘（单项检查）"
                        },
                        {
                            "id": 50,
                            "name": "哮喘COPD检查"
                        }
                    ],
                    "id": 3,
                    "name": "慢阻肺"
                },
                {
                    "examineTypeList": [
                        {
                            "id": 21,
                            "name": "肝功能"
                        },
                        {
                            "id": 22,
                            "name": "肾功能"
                        },
                        {
                            "id": 45,
                            "name": "血常规"
                        },
                        {
                            "id": 51,
                            "name": "血糖检查"
                        },
                        {
                            "id": 52,
                            "name": "血脂化检查"
                        },
                        {
                            "id": 53,
                            "name": "电解质检查"
                        },
                        {
                            "id": 54,
                            "name": "脑血管造影"
                        },
                        {
                            "id": 55,
                            "name": "头颈部磁共振血管造影（MRA）"
                        },
                        {
                            "id": 56,
                            "name": "高分辨磁共振成像（HRMRI）"
                        },
                        {
                            "id": 57,
                            "name": "颈动脉B型超生检查"
                        },
                        {
                            "id": 58,
                            "name": "经颅多普勒超生探测"
                        },
                        {
                            "id": 59,
                            "name": "CTA检查"
                        },
                        {
                            "id": 60,
                            "name": "DSA"
                        },
                        {
                            "id": 61,
                            "name": "动态心电图检查"
                        }
                    ],
                    "id": 4,
                    "name": "脑卒中"
                }
            ]
        },
        "success": true
    }

# 服务者新增profile [POST /enterprise/profile/save]

修改服务者名称

请求字段说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|Y|帐号token|
|companyId|Long|Y|企业ID|
|profileId|Long|Y|profileId为0新增，负责为修改|
|birthday|String|Y|"1988-06-23"|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
  {
    "token"       :   "a6cbab6095b24a93b3f5537335062154",
    "companyId"   :   6,
    "profileId"   :   0,
    "birthday"    :   "1988-06-23",
    "name"        :   "小李",
    "sex"         :   0,
    "iid"         :   ""
  }

+ Response 200 (application/json)
  {
      "code": 1,
      "data": {
          "info": {
              "birthday": "1988-06-23",
              "companyId": 6,
              "id": 1910009,
              "iid": "",
              "name": "小李",
              "profileId": 1910009,
              "sex": 0,
              "token": "a6cbab6095b24a93b3f5537335062154"
          }
      },
      "success": true
  }

# 服务者查询profile列表 [POST /enterprise/profile/list]

服务者查询profile列表

参数说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|APP必须有/PC不需要|用户登录token|
|companyId|Long|Y|机构id|
|id|Long|Y|当前病历id|
|type|Integer|Y|默认下一页0（返回小于病历id的数据） 上一页1（返回大于病历id的数据）|

返回字段说明：
|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|状态码|
|data|Object|返回结果数据|


+ Request (application/json)
  {
    "token"       :"a6cbab6095b24a93b3f5537335062154",
    "companyId"   :6,
    "id"          :1910002,
    "type"        :1,
    "pageSize":20
  }

+ Response 200 (application/json)
  {
      "code": 1,
      "data": {
          "total": 4,
          "list": [
              {
                  "age": 0,
                  "birthday": "2016-01-01",
                  "companyId": 6,
                  "iid": "421023198803160412",
                  "name": "gongchao",
                  "profileId": 1910052,
                  "sex": 0
              },
              {
                  "age": 0,
                  "birthday": "1926-01-01",
                  "companyId": 6,
                  "iid": "220303111111111111",
                  "name": "测试患者",
                  "profileId": 1910045,
                  "sex": 0
              },
              {
                  "age": 0,
                  "birthday": "1924-01-01",
                  "companyId": 6,
                  "iid": "111111111111111111",
                  "name": "dfgfgghhhhh",
                  "profileId": 1910043,
                  "sex": 0
              },
              {
                  "age": 0,
                  "birthday": "1924-01-01",
                  "companyId": 6,
                  "iid": "222222222222222222",
                  "name": "gfdf",
                  "profileId": 1910041,
                  "sex": 0
              }
          ]
      },
      "success": true
  }


# 服务者profile详情 [GET /enterprise/profile/{token}/{profileId}/{companyId}]

profile详情

参数说明：
|Field | 说明 |
| -- | -- |
| token | 用户token |
|profileId|profileId|
|companyId|机构id|

+ Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
      + profileId:1910106(required,String) - companyGroup
      + companyId:6(required,String) - 当前accountId下的profileId
+ Request (application/json)

+ Response 200 (application/json)
{
    "code": 1,
    "data": {
        "info": {
            "age": 25,
            "birthday": "1991-05-07",
            "companyId": 6,
            "iid": "411402199105077016",
            "name": "hello",
            "profileId": 1910106,
            "sex": 0,
            "token": "18150c3abc6b461cad4db70e53547629"
        }
    },
    "success": true
}


# 诊断列表 [POST /enterprise/diagnosis/list]

profile详情

参数说明:
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|APP必须有/PC不需要|用户登录token|
|id|Integer|Y|诊断id|
|type|Integer|Y|默认下一页0（返回小于诊断id的数据） 上一页1（返回大于诊断id的数据）|
|uid|Integer|Y|患者Id|
|companyId|Integer|Y|服务者的组织Id|
|pageSize|Integer|Y|分页大小|

返回参数
```json
{
    "code": 1,
    "data": {
        "total":100,//总记录数量
        "list": [
            {
                "id":100,
                "type":1,//诊断类型ID
                "complaint":"",//主述
        "resultIllness":"",//诊断结果_病情
        "resultDiagnosis":"",//诊断结果_诊断
        "resultMedicine":"",//诊断结果_用药
                "time": "yyyyMMddHHmmss",//创建时间
                "status":1,//状态.0=正在诊断.1=诊断完成
                "read":1//是否已阅 0=未读 1=已读
            },
            {
                "id":100,
                "type":1,//诊断类型ID
                "complaint":"",//主述
        "resultIllness":"",//诊断结果_病情
        "resultDiagnosis":"",//诊断结果_诊断
        "resultMedicine":"",//诊断结果_用药
                "time": "yyyyMMddHHmmss",//创建时间
                "status":1,//状态.0=正在诊断.1=诊断完成
                "read":1//是否已阅 0=未读 1=已读
            },
            {
                "id":100,
                "type":1,//诊断类型ID
                "complaint":"",//主述
        "resultIllness":"",//诊断结果_病情
        "resultDiagnosis":"",//诊断结果_诊断
        "resultMedicine":"",//诊断结果_用药
                "time": "yyyyMMddHHmmss",//创建时间
                "status":1,//状态.0=正在诊断.1=诊断完成
                "read":1//是否已阅 0=未读 1=已读
            }
        ]
    },
    "success": true
}
```

+ Request (application/json)
{
  "token": "605d24b946c94690b2c34dcae2c369d1",
  "uid": 1910375,
  "id": 1,
  "type": 1,
  "pageSize": 10,
  "companyId":6
}
+ Response 200 (application/json)
{
  "code": 1,
  "data": {
    "total": 4,
    "list": [
      {
        "complaint": "图表",
        "id": 1158,
        "read": 0,
        "status": 1,
        "taskNum": "31473479649409006579",
        "time": "20160910115409",
        "type": 3,
        "userId": 1910375,
        "userName": "慢阻肺患者"
      },
      {
        "complaint": "图",
        "id": 1157,
        "read": 0,
        "status": 1,
        "taskNum": "31473479523219006025",
        "time": "20160910115203",
        "type": 3,
        "userId": 1910375,
        "userName": "慢阻肺患者"
      },
      {
        "complaint": "表。。。。。",
        "id": 1156,
        "read": 0,
        "status": 1,
        "taskNum": "31473479407339006034",
        "time": "20160910115007",
        "type": 3,
        "userId": 1910375,
        "userName": "慢阻肺患者"
      },
      {
        "complaint": "空",
        "id": 1155,
        "read": 0,
        "status": 1,
        "taskNum": "31473479342970006222",
        "time": "20160910114903",
        "type": 3,
        "userId": 1910375,
        "userName": "慢阻肺患者"
      }
    ]
  },
  "success": true
}

# 申请诊断-高血压 [POST /enterprise/diagnosis/hbp]

申请诊断-高血压
```json

{
    "token": "4243c0221cc53388a9242aa41b2c91ca",  //服务者token
    "userId": 501042,  //患者id
    "applyCompId": 6,  //申请机构id
    "handleCompId": 6,  //请求机构id
    "complaint": "患者主诉信息",
    "hbpDto": {
        "bpDataList": [  //非同日血压值
            {
                "date": "2016-06-23 12:00:00",
                "dbp": "90",  //舒张压,低压
                "sbp": "110"  //收缩压,高压
            },
            {
                "date": "2016-06-24 14:12:23",
                "dbp": "100",
                "sbp": "130"
            },
            {
                "date": "2016-07-12 12:28:01",
                "dbp": "80",
                "sbp": "100"
            }
        ],
        "imageGroups": [  //照片组
            {
                "id": 1,  //照片类型id
                "name": "尿常规化验",
                "imageDataList": [{  //照片数据
                    "name": "尿常规1",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                },{
                    "name": "尿常规2",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                }]
            },
            {
                "id": 2,
                "name": "血液血红蛋白化验",
                "imageDataList": [{
                    "name": "血液",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                }]
            }
        ]
    }
}

```


+ Request (application/json)
{
    "token": "4243c0221cc53388a9242aa41b2c91ca",
    "userId": 501042,
    "applyCompId": 6,
    "handleCompId": 6,
    "complaint": "患者主诉信息",
    "hbpDto": {
        "bpDataList": [
            {
                "date": "2016-06-23 12:00:00",
                "dbp": "90",
                "sbp": "110"
            },
            {
                "date": "2016-06-24 14:12:23",
                "dbp": "100",
                "sbp": "130"
            },
            {
                "date": "2016-07-12 12:28:01",
                "dbp": "80",
                "sbp": "100"
            }
        ],
        "imageGroups": [
            {
                "id": 1,
                "name": "尿常规化验",
                "imageDataList": [{
                    "name": "尿常规1",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                },{
                    "name": "尿常规2",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                }]
            },
            {
                "id": 2,
                "name": "血液血红蛋白化验",
                "imageDataList": [{
                    "name": "血液",
                    "pic": "https://www.baidu.com/img/bd_logo1.png",
                    "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                    "largePic": "https://www.baidu.com/img/bd_logo1.png"
                }]
            }
        ]
    }
}
+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 申请诊断-糖尿病 [POST /enterprise/diagnosis/dm]

申请诊断-糖尿病


```json
{
    "userId": 501042,
    "handleCompId": 6,
    "complaint": "患者主诉",
    "applyCompId":"6",
    "token":"a4460236c83545dfa7a6d008dbc2436f",
    "dmForm": {
        "physicalCheck":{
            "stature":110,
            "weight":110,
            "bmi":110,
            "waistline":110
        },
        "bpData":{
            "dbp":120,
            "sbp":120,
            "date":"2016-06-28"
        },
        "dpap":"减弱",
        "imageGroups":[
                {"id":1,"name":"糖尿病足足背动脉检查",
                "imageDataList":[
                    {
                    "name":"糖尿病足足背动脉检查1",
                    "pic":"https://www.baidu.com/img/bd_logo1.png",
                    "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                    "largePic":"https://www.baidu.com/img/bd_logo1.png"
                    },
                    {
                    "name":"糖尿病足足背动脉检查2",
                    "pic":"https://www.baidu.com/img/bd_logo1.png",
                    "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                    "largePic":"https://www.baidu.com/img/bd_logo1.png"
                    }
                    ]
                },
                {
                    "id":2,
                    "name":"血糖化验",
                    "imageDataList":[
                        {
                            "name":"血糖化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"血糖化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                },
                {
                    "id":3,
                    "name":"低密度脂蛋白胆固醇化验",
                    "imageDataList":[
                        {
                            "name":"低密度脂蛋白胆固醇化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"低密度脂蛋白胆固醇化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                },
                {
                    "id":4,
                    "name":"甘油三酯化验",
                    "imageDataList":[
                        {
                            "name":"甘油三酯化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"甘油三酯化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                }
        ]
    }
}

```
+ Request (application/json)
{
    "userId": 501042,
    "handleCompId": 6,
    "complaint": "患者主诉",
    "applyCompId":"6",
    "token":"a4460236c83545dfa7a6d008dbc2436f",
    "dmForm": {
        "physicalCheck":{
            "stature":110,
            "weight":110,
            "bmi":110,
            "waistline":110
        },
        "bpData":{
            "dbp":120,
            "sbp":120,
            "date":"2016-06-28"
        },
        "dpap":"减弱",
        "imageGroups":[
                {"id":1,"name":"糖尿病足足背动脉检查",
                "imageDataList":[
                    {
                    "name":"糖尿病足足背动脉检查1",
                    "pic":"https://www.baidu.com/img/bd_logo1.png",
                    "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                    "largePic":"https://www.baidu.com/img/bd_logo1.png"
                    },
                    {
                    "name":"糖尿病足足背动脉检查2",
                    "pic":"https://www.baidu.com/img/bd_logo1.png",
                    "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                    "largePic":"https://www.baidu.com/img/bd_logo1.png"
                    }
                    ]
                },
                {
                    "id":2,
                    "name":"血糖化验",
                    "imageDataList":[
                        {
                            "name":"血糖化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"血糖化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                },
                {
                    "id":3,
                    "name":"低密度脂蛋白胆固醇化验",
                    "imageDataList":[
                        {
                            "name":"低密度脂蛋白胆固醇化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"低密度脂蛋白胆固醇化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                },
                {
                    "id":4,
                    "name":"甘油三酯化验",
                    "imageDataList":[
                        {
                            "name":"甘油三酯化验1",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        },
                        {
                            "name":"甘油三酯化验2",
                            "pic":"https://www.baidu.com/img/bd_logo1.png",
                            "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                            "largePic":"https://www.baidu.com/img/bd_logo1.png"
                        }
                    ]
                }
        ]
    }
}
+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 申请诊断-脑卒中 [POST /enterprise/diagnosis/ca]

申请诊断-脑卒中


```json
{
    "token":"这是服务者token",
    "userId":10,   //病患ID
    "handleCompId":10,//处理机构ID
    "complaint":"", //主诉
    "caForm":{
                  "bpDataList": [ //非同日血压值
                        {
                            "dpb":0, //舒张压
                            "sbp":0, //收缩压
                            "date":"yyyy-MM-dd HH:mm"//测量时间
                        },
                        {
                            "dpb":0,
                            "sbp":0,
                            "date":null
                        },
                        {
                            "dpb":0,
                            "sbp":0,
                            "date":null
                        }],
                  "hb": null,//血红蛋白(130-175)[g/L(克/升)]
                  "bptr": null, //血钾化验结果Blood potassium test result [(3.5--5.5)(mmol/l)]
                  "scar": null,//血肌酐化验结果 Serum creatinine assay results [(0--115) μmoI/L]
                  "uaar": null,  //尿酸化验结果 Uric acid assay results [(125--440) μmoI/L]
                  "bloodLipidAssay": {   //血脂化验结果
                      "angiotensin": 0,  //血管紧张素 (10～30 ng/L)
                      "cholesterol": 0, //总胆固醇 (<5.2 mmol/L)
                      "apolipoproteinA1": 0, //载脂蛋白A1 (1.0--2.0 g/l)
                      "hemoglobin": 0, //糖化血红蛋白量 (0.5--4 4.5-6.3%)
                      "hdl": null, //高密度脂蛋白 High density lipoprotein (0.9--3.1 mmol/L)
                      "ldl": 0, //低密度脂蛋白 Low density lipoprotein (<3.61 mmol/L)
                      "triglyceride": 0,//甘油三酯 (<1.7 mmol/L)
                      "lipoprotein": 0,  //脂蛋白 (10～140 mmol/L)
                      "apolipoproteinB": 0, //载脂蛋白B (<1.05 g/L)
                      "sod": 0  //超氧化物歧化酶Superoxide dismutase (242～620 U/L)
                  },
                  "bpOtherData": {//高血压其他辅助信息
                      "ecgReport": null, //心电图报告
                      "fundus": null,  //眼底
                      "renalArtery": null, //肾动脉
                      "cau": null,//颈动脉彩超Carotid artery ultrasonography
                      "hcdu": null, //心彩超 heart Colour Doppler Ultrasound
                      "kcdu": null,//肾彩超 kidney Colour Doppler Ultrasound
                      "alt": null,//醛固酮立卧位实验 Aldosterone level test
                      "ureaNitrogen": null//尿素氮 Urea nitrogen
                  },
                  "physicalCheck": { //体格检查
                      "stature": null,//身高
                      "weight": null,//体重
                      "bmi": null,//体质指数，（BMI）=体重（kg）÷身高（m）^2
                      "waistline": null//腰围
                  },
                  "bpData": {//血压
                      "dbp": 0,//舒张压
                      "sbp": 0,//收缩压
                      "date": null
                  },
                  "dpap": null, //足背动脉搏动(手触);正常0，减弱1，可疑2，消失3
                  "dfdae": null,//糖尿病足足背动脉检查
                  "bloodCheck": { //化验检查（抽血）
                      "emptyBg": null,//空腹血糖（3.6-6.1毫摩/升）
                      "afterBg1": null,//餐后血糖 (餐后1小时：6.7-11.1毫摩/升）
                      "afterBg2": null, //餐后血糖 (餐后2小时：≤7.8毫摩/升）
                      "afterBg3": null, //餐后血糖 (餐后3小时：恢复正常值）
                      "hbA1c": null,//糖化血红蛋白(HbA1c):3.5—6.5mol/L
                      "ldlc": null,//低密度脂蛋白胆固醇（LDLC）: ＜3.61mol/L
                      "tg": null,//甘油三酯（TG）: <1.7 mol/L
                      "tc": null,//总胆固醇(TC): <5.2 mol/L
                      "hdlc": null//高密度脂蛋白胆固醇（HDLC）: 0.9--3.1 mol/L
                  },
                  "ru": {//尿常规
                   "color":null,     //颜色；
                      "turb": null,//浊度
                      "sg": null,//集中
                      "ph": null,//PH
                      "ket": null, //酮体
                      "uro": null,//尿胆原
                      "bil": null,//胆红素
                      "leu": null,//白细胞
                      "bld": null,//隐血
                      "pro": null,//倒班制
                      "nit": null,//亚硝酸盐
                      "glu": null//葡萄糖
                  },
                  "lf": {//肝功能
                      "hBsAg": null,//乙肝病毒表面抗原
                      "hBsAb": null,//乙肝病毒便面抗体
                      "hBeAg": null,//乙肝病毒ｅ抗原
                      "hBeAb": null,//乙肝病毒ｅ抗体
                      "hBcAb": null,//乙肝病毒核心抗体
                      "antiHCV": null,//丙型肝炎病毒抗体
                      "antiHIV1_2": null,//HIV1+2抗体初筛试验
                      "antiTP": null//梅毒抗体初筛试验
                  },
                  "rf": {//肾功能
                      "urea": null,//尿素
                      "b2mg": null,//B2微球蛋白
                      "creatinine": null,//肌酐
                      "ua": null,//尿酸
                      "a1mg": null,//a1微球蛋白
                      "cystatinC": null//胱抑素C
                  },
                  "tsh": null,//促甲状腺激素(TSH)
                  "fe": null,//眼底检查
                  "ecg": null,//心电图
                  "nc": {//神经病变相关检查
                      "snCheck": null,//感觉神经的检查
                      "mnCheck": null,//运动神经的检查
                      "anCheck": null,//自主神经的检查
                      "nrCheck": null//神经根、近端运动神经、颅神经及单神经病变的检查
                  },
                  "ua": {//尿白蛋白
                      "uta": null,//尿微量白蛋白
                      "cr": null//尿肌酐(Cr)
                  },
                  "sifCheck": null,//同步胰岛功能检查
                  "ia": null,//胰岛素抗体
                  "acr": null,//尿ACR
                  "taCheck": null,//甲状腺抗体检查
                  "lfe": null,// 肺功能检查（必添项）
                  "lfl": null,//肺功能分级0.危险状态1.轻度2.中度3.重度4.极重度
                  "cxe": null,//胸部X线检查
                  "ccte": null,//胸部CT检查（必添项）
                  "bge": {//血气检查
                      "bloodPH": null,//酸碱度（pH）
                      "pco2": null,//二氧化碳分压（PCO2）
                      "tco2": null,//二氧化碳总量（TCO2）
                      "po2": null,//氧分压（PO2）
                      "sato2": null,//氧饱和度（SatO2）
                      "bicarbonate": null,//碳酸氢根（AB）
                      "realityBicarbonate": null,//实际碳酸氢根（AB）
                      "be": null,//剩余碱（BE）
                      "ag": null//阴离子隙（AG）
                  },
                  "rfc": null,//呼吸衰竭检查
                  "loc": {//肺部其他检查信息
                      "pulseOxygenMonitoring": null,//脉氧监测
                      "o2detecting": null,//O2检测
                      "co2detecting": null,//CO2检测
                      "infectionImmunityMonitoring": null,//感染免疫监测
                      "complicationMonitoring": null//并发症监测(气胸、双下肢水肿)
                  },
                  "lfi": {//肺部进一步检查信息
                      "bloodRoutine": null,//血常规
                      "sputumCulture": null,//痰培养(急性加重期怀疑细菌感染)
                      "fungusDetection": null,//G试验、GM试验(急性加重期怀疑真菌感染)
                      "asthma": null//哮喘（单项检查）或哮喘COPD检查
                  },
                  "rbt": null,//血常规检查 routineBloodTest
                  "electrolyte": null,//电解质检查
                  "brainAngiography": null,//脑血管造影
                  "mra": null,//头颈部磁共振血管造影（MRA）或高分辨磁共振成像（HRMRI）
                  "cb": null,//颈动脉B型超声检查和经颅多普勒超声探测
                  "cta": null,//CTA检查（或DSA、MRA）
                  "holter": null//动态心电图检查
    }
}

```
+ Request (application/json)
{
    "token": "605d24b946c94690b2c34dcae2c369d1",
    "userId": 10,
    "handleCompId": 10,
    "complaint": "",
    "caForm": {
        "bpDataList": [
            {
                "dpb": 0,
                "sbp": 0,
                "date": "yyyy-MM-dd HH:mm"
            },
            {
                "dpb": 0,
                "sbp": 0,
                "date": null
            },
            {
                "dpb": 0,
                "sbp": 0,
                "date": null
            }
        ],
        "hb": null,
        "bptr": null,
        "scar": null,
        "uaar": null,
        "bloodLipidAssay": {
            "angiotensin": 0,
            "cholesterol": 0,
            "apolipoproteinA1": 0,
            "hemoglobin": 0,
            "hdl": null,
            "ldl": 0,
            "triglyceride": 0,
            "lipoprotein": 0,
            "apolipoproteinB": 0,
            "sod": 0
        },
        "bpOtherData": {
            "ecgReport": null,
            "fundus": null,
            "renalArtery": null,
            "cau": null,
            "hcdu": null,
            "kcdu": null,
            "alt": null,
            "ureaNitrogen": null
        },
        "physicalCheck": {
            "stature": null,
            "weight": null,
            "bmi": null,
            "waistline": null
        },
        "bpData": {
            "dbp": 0,
            "sbp": 0,
            "date": null
        },
        "dpap": null,
        "dfdae": null,
        "bloodCheck": {
            "emptyBg": null,
            "afterBg1": null,
            "afterBg2": null,
            "afterBg3": null,
            "hbA1c": null,
            "ldlc": null,
            "tg": null,
            "tc": null,
            "hdlc": null
        },
        "ru": {
            "color": null,
            "turb": null,
            "sg": null,
            "ph": null,
            "ket": null,
            "uro": null,
            "bil": null,
            "leu": null,
            "bld": null,
            "pro": null,
            "nit": null,
            "glu": null
        },
        "lf": {
            "hBsAg": null,
            "hBsAb": null,
            "hBeAg": null,
            "hBeAb": null,
            "hBcAb": null,
            "antiHCV": null,
            "antiHIV1_2": null,
            "antiTP": null
        },
        "rf": {
            "urea": null,
            "b2mg": null,
            "creatinine": null,
            "ua": null,
            "a1mg": null,
            "cystatinC": null
        },
        "tsh": null,
        "fe": null,
        "ecg": null,
        "nc": {
            "snCheck": null,
            "mnCheck": null,
            "anCheck": null,
            "nrCheck": null
        },
        "ua": {
            "uta": null,
            "cr": null
        },
        "sifCheck": null,
        "ia": null,
        "acr": null,
        "taCheck": null,
        "lfe": null,
        "lfl": null,
        "cxe": null,
        "ccte": null,
        "bge": {
            "bloodPH": null,
            "pco2": null,
            "tco2": null,
            "po2": null,
            "sato2": null,
            "bicarbonate": null,
            "realityBicarbonate": null,
            "be": null,
            "ag": null
        },
        "rfc": null,
        "loc": {
            "pulseOxygenMonitoring": null,
            "o2detecting": null,
            "co2detecting": null,
            "infectionImmunityMonitoring": null,
            "complicationMonitoring": null
        },
        "lfi": {
            "bloodRoutine": null,
            "sputumCulture": null,
            "fungusDetection": null,
            "asthma": null
        },
        "rbt": null,
        "electrolyte": null,
        "brainAngiography": null,
        "mra": null,
        "cb": null,
        "cta": null,
        "holter": null
    }
}
+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 申请诊断-慢阻肺 [POST /enterprise/diagnosis/copd]

申请诊断-慢阻肺


```json
{
    "token": "4243c0221cc53388a9242aa41b2c91ca",//服务者token
    "userId": 501042,//患者id
    "applyCompId": 6,//申请机构id
    "handleCompId": 6,//请求机构id
    "complaint": "患者主诉信息",
    "copdForm":{
          "lfl":1,    //肺功能分级10.危险状态  20.轻度  30.中度  40.重度  50.极重度
            "lfe":{
                 "name":"mingzi",//图片名称
                 "pic":"https://www.baidu.com/img/bd_logo1.png",//原始图片
                 "smallPic":"https://www.baidu.com/img/bd_logo1.png", //小图
                 "largePic":"https://www.baidu.com/img/bd_logo1.png"//大图
            },// 肺功能检查（必添项）
            "ccte":{
                 "name":"mingzi",//图片名称
                 "pic":"https://www.baidu.com/img/bd_logo1.png",//原始图片
                 "smallPic":"https://www.baidu.com/img/bd_logo1.png", //小图
                 "largePic":"https://www.baidu.com/img/bd_logo1.png"//大图
            },    //胸部CT检查（必添项）
         "imageGroups": [  //照片组
             {
                 "id": 1,  //照片类型id
                 "name": "尿常规化验",
                 "imageDataList": [{  //照片数据
                     "name": "尿常规1",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"
                 },{
                     "name": "尿常规2",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"
                 }]
             },
             {
                 "id": 2,
                 "name": "血液血红蛋白化验",
                 "imageDataList": [{
                     "name": "血液",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"

                 }]
             }
         ]
     }
 }

```
+ Request (application/json)
{
    "token": "4243c0221cc53388a9242aa41b2c91ca",
    "userId": 501042,
    "applyCompId": 6,
    "handleCompId": 6,
    "complaint": "患者主诉信息",
    "copdForm":{
          "lfl":1,
            "lfe":{
                 "name":"mingzi",
                 "pic":"https://www.baidu.com/img/bd_logo1.png",
                 "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                 "largePic":"https://www.baidu.com/img/bd_logo1.png"
            },
            "ccte":{
                 "name":"mingzi",
                 "pic":"https://www.baidu.com/img/bd_logo1.png",
                 "smallPic":"https://www.baidu.com/img/bd_logo1.png",
                 "largePic":"https://www.baidu.com/img/bd_logo1.png"
            },
         "imageGroups": [
             {
                 "id": 1,
                 "name": "尿常规化验",
                 "imageDataList": [{
                     "name": "尿常规1",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"
                 },{
                     "name": "尿常规2",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"
                 }]
             },
             {
                 "id": 2,
                 "name": "血液血红蛋白化验",
                 "imageDataList": [{
                     "name": "血液",
                     "pic": "https://www.baidu.com/img/bd_logo1.png",
                     "smallPic": "https://www.baidu.com/img/bd_logo1.png",
                     "largePic": "https://www.baidu.com/img/bd_logo1.png"
                 }]
             }
         ]
     }
}
+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}


# 获取诊断详情 [GET /enterprise/diagnosis/detail?token={token}&taskId={taskId}&companyId={companyId}]

获取诊断详情接口

参数说明:

|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|APP必须有/PC不需要|用户登录token|
|taskId|Integer|Y|诊断任务Id|
|companyId|Integer|Y|服务者组织Id|


```json
{
    "code": 1,
    "data": {
       "task":{
    "id": 1, //诊断任务编号
    "taskNum": "11466505309013001982", //任务号
    "type": 1, //病种
    "userId": 1, //病患id
    "userName": "", //病患姓名
    "complaint":"",//主述
    "resultIllness":"",//诊断结果_病情
    "resultDiagnosis":"",//诊断结果_诊断
    "resultMedicine":"",//诊断结果_用药
        "time": "yyyyMMddHHmmss",//创建时间
        "status":1,//状态.0=正在诊断.1=诊断完成
        "read":1,//是否已阅 0=未读 1=已读
    "form":{
       "bpDataList": [ //非同日血压值
           {
             "dpb":0, //舒张压
             "sbp":0, //收缩压
             "date":"yyyy-MM-dd HH:mm"//测量时间
           },
           {
             "dpb":0,
             "sbp":0,
             "date":null
           },
           {
             "dpb":0,
             "sbp":0,
             "date":null
             }
        ],
       "hb": null,//血红蛋白(130-175)[g/L(克/升)]
       "bptr": null, //血钾化验结果Blood potassium test result [(3.5--5.5)(mmol/l)]
       "scar": null,//血肌酐化验结果 Serum creatinine assay results [(0--115) μmoI/L]
       "uaar": null,  //尿酸化验结果 Uric acid assay results [(125--440) μmoI/L]
       "bloodLipidAssay": {   //血脂化验结果
         "angiotensin": 0,  //血管紧张素 (10～30 ng/L)
         "cholesterol": 0, //总胆固醇 (<5.2 mmol/L)
         "apolipoproteinA1": 0, //载脂蛋白A1 (1.0--2.0 g/l)
         "hemoglobin": 0, //糖化血红蛋白量 (0.5--4 4.5-6.3%)
         "hdl": null, //高密度脂蛋白 High density lipoprotein (0.9--3.1 mmol/L)
         "ldl": 0, //低密度脂蛋白 Low density lipoprotein (<3.61 mmol/L)
         "triglyceride": 0,//甘油三酯 (<1.7 mmol/L)
         "lipoprotein": 0,  //脂蛋白 (10～140 mmol/L)
         "apolipoproteinB": 0, //载脂蛋白B (<1.05 g/L)
         "sod": 0  //超氧化物歧化酶Superoxide dismutase (242～620 U/L)
       },
       "bpOtherData": {//高血压其他辅助信息
         "ecgReport": null, //心电图报告
         "fundus": null,  //眼底
         "renalArtery": null, //肾动脉
         "cau": null,//颈动脉彩超Carotid artery ultrasonography
         "hcdu": null, //心彩超 heart Colour Doppler Ultrasound
         "kcdu": null,//肾彩超 kidney Colour Doppler Ultrasound
         "alt": null,//醛固酮立卧位实验 Aldosterone level test
         "ureaNitrogen": null//尿素氮 Urea nitrogen
       },
       "physicalCheck": { //体格检查
         "stature": null,//身高
         "weight": null,//体重
         "bmi": null,//体质指数，（BMI）=体重（kg）÷身高（m）^2
         "waistline": null//腰围
       },
       "bpData": {//血压
         "dbp": 0,//舒张压
         "sbp": 0,//收缩压
         "date": null
       },
       "dpap": null, //足背动脉搏动(手触);正常0，减弱1，可疑2，消失3
       "dfdae": null,//糖尿病足足背动脉检查
       "bloodCheck": { //化验检查（抽血）
         "emptyBg": null,//空腹血糖（3.6-6.1毫摩/升）
         "afterBg1": null,//餐后血糖 (餐后1小时：6.7-11.1毫摩/升）
         "afterBg2": null, //餐后血糖 (餐后2小时：≤7.8毫摩/升）
         "afterBg3": null, //餐后血糖 (餐后3小时：恢复正常值）
         "hbA1c": null,//糖化血红蛋白(HbA1c):3.5—6.5mol/L
         "ldlc": null,//低密度脂蛋白胆固醇（LDLC）: ＜3.61mol/L
         "tg": null,//甘油三酯（TG）: <1.7 mol/L
         "tc": null,//总胆固醇(TC): <5.2 mol/L
         "hdlc": null//高密度脂蛋白胆固醇（HDLC）: 0.9--3.1 mol/L
       },
       "ru": {//尿常规
         "color":null,         //颜色；
         "turb": null,//浊度
         "sg": null,//集中
         "ph": null,//PH
         "ket": null, //酮体
         "uro": null,//尿胆原
         "bil": null,//胆红素
         "leu": null,//白细胞
         "bld": null,//隐血
         "pro": null,//倒班制
         "nit": null,//亚硝酸盐
         "glu": null//葡萄糖
       },
       "lf": {//肝功能
         "hBsAg": null,//乙肝病毒表面抗原
         "hBsAb": null,//乙肝病毒便面抗体
         "hBeAg": null,//乙肝病毒ｅ抗原
         "hBeAb": null,//乙肝病毒ｅ抗体
         "hBcAb": null,//乙肝病毒核心抗体
         "antiHCV": null,//丙型肝炎病毒抗体
         "antiHIV1_2": null,//HIV1+2抗体初筛试验
         "antiTP": null//梅毒抗体初筛试验
       },
       "rf": {//肾功能
         "urea": null,//尿素
         "b2mg": null,//B2微球蛋白
         "creatinine": null,//肌酐
         "ua": null,//尿酸
         "a1mg": null,//a1微球蛋白
         "cystatinC": null//胱抑素C
       },
       "tsh": null,//促甲状腺激素(TSH)
       "fe": null,//眼底检查
       "ecg": null,//心电图
       "nc": {//神经病变相关检查
         "snCheck": null,//感觉神经的检查
         "mnCheck": null,//运动神经的检查
         "anCheck": null,//自主神经的检查
         "nrCheck": null//神经根、近端运动神经、颅神经及单神经病变的检查
       },
       "ua": {//尿白蛋白
         "uta": null,//尿微量白蛋白
         "cr": null//尿肌酐(Cr)
       },
       "sifCheck": null,//同步胰岛功能检查
       "ia": null,//胰岛素抗体
       "acr": null,//尿ACR
       "taCheck": null,//甲状腺抗体检查
       "lfe": null,// 肺功能检查（必添项）
       "lfl": null,//肺功能分级0.危险状态1.轻度2.中度3.重度4.极重度
       "cxe": null,//胸部X线检查
       "ccte": null,//胸部CT检查（必添项）
       "bge": {//血气检查
         "bloodPH": null,//酸碱度（pH）
         "pco2": null,//二氧化碳分压（PCO2）
         "tco2": null,//二氧化碳总量（TCO2）
         "po2": null,//氧分压（PO2）
         "sato2": null,//氧饱和度（SatO2）
         "bicarbonate": null,//碳酸氢根（AB）
         "realityBicarbonate": null,//实际碳酸氢根（AB）
         "be": null,//剩余碱（BE）
         "ag": null//阴离子隙（AG）
       },
       "rfc": null,//呼吸衰竭检查
       "loc": {//肺部其他检查信息
         "pulseOxygenMonitoring": null,//脉氧监测
         "o2detecting": null,//O2检测
         "co2detecting": null,//CO2检测
         "infectionImmunityMonitoring": null,//感染免疫监测
         "complicationMonitoring": null//并发症监测(气胸、双下肢水肿)
       },
       "lfi": {//肺部进一步检查信息
         "bloodRoutine": null,//血常规
         "sputumCulture": null,//痰培养(急性加重期怀疑细菌感染)
         "fungusDetection": null,//G试验、GM试验(急性加重期怀疑真菌感染)
         "asthma": null//哮喘（单项检查）或哮喘COPD检查
       },
       "rbt": null,//血常规检查 routineBloodTest
       "electrolyte": null,//电解质检查
       "brainAngiography": null,//脑血管造影
       "mra": null,//头颈部磁共振血管造影（MRA）或高分辨磁共振成像（HRMRI）
       "cb": null,//颈动脉B型超声检查和经颅多普勒超声探测
       "cta": null,//CTA检查（或DSA、MRA）
       "holter": null//动态心电图检查,
       "imageGroups": [{ //图片按类别分组
        "name": "",
        "imageDataList": [{
          "name": "", //图片名称
          "pic": "", //原始图片
          "smallPic": "", //小图
          "largePic": "" //大图
        }, ...]
       },
       ...
       ]
      }
     }
    },
    "success": true
}
```
+ Parameters
    + token:d2a6771570c44817b18fdbcfa25891e7 (required,String) - 用户登录后的token
    + taskId:1105(required,number) - 诊断id
    + companyId:6(required,number) -companyId企业
+ Request (application/json)

+ Response 200 (application/json)
{
  "code": 1,
  "data": {
    "task": {
      "complaint": "脑卒中客户端发起",
      "form": {
        "imageGroups": [
          {
            "id": 51,
            "imageDataList": [
              {
                "largePic": "http://files-test.cim120.cn/hmp/detection/f/900035/1903201/30d6f9937fd375dfb48c77e0f5d1c47db6dcb965_large.jpg",
                "pic": "http://files-test.cim120.cn/hmp/detection/f/900035/1903201/30d6f9937fd375dfb48c77e0f5d1c47db6dcb965.jpg",
                "smallPic": "http://files-test.cim120.cn/hmp/detection/f/900035/1903201/30d6f9937fd375dfb48c77e0f5d1c47db6dcb965_small.jpg"
              }
            ],
            "name": "血糖检查"
          }
        ],
        "physicalCheck": {
          "bmi": "55.5",
          "stature": "60",
          "waistline": "30",
          "weight": "20"
        }
      },
      "id": 1105,
      "read": 0,
      "status": 1,
      "taskNum": "41473320904650006336",
      "time": "20160918110254",
      "type": 4,
      "userId": 1903201,
      "userName": "杨正祥"
    }
  },
  "success": true
}

# 添加日常健康数据 [POST /enterprise/health/save]
保存日常健康数据

请求参数:

```js
{
    "info": "此处为具体测量数据的json信息",
    "itemType": 3,//测量类型:1=血压  2=服药  3=体温 4=体重 5=心率 6=身高 7=血氧 8=血糖 9=呼吸率
    "orginId": 7777,//对应的机构编号
    "profileId": 9999,//对应的病患编号
    "staffId": 12345,//服务者编号
    "time": "20160630123443",//数据收集时间
    "token": "xxxxxx"
}

血压对应的json
{"dbp":70,"sbp":100}
服药对应的json
[{"name":"阿莫西林","type":1},{"name":"脑残片","type":2}]
体温数据对应的json
{"bt":39.5}
体重数据对应的json
{"bw":63.9}
心率数据对应的json
{"hr":79}
身高对应的json
{"height":79}
血氧对应的json
{"bloodOx":79}
血糖对应的json
{
"empty": 7.0,    //空腹血糖
"emptyTime": "201609061120221",   //测量时间
"oneHour":13.2 ,    //1小时血糖
"oneTime":"20160906130221" ,   //时间
"twoHour": 11.1,    //2小时血糖
"twoTime": "20160906140221",   //时间
"threeHour": 8.6,   //3小时血糖
"threeTime": "20160906150221",  //时间
}
呼吸率对应的json
{"beath",20}
```
响应结果:
```js
{
  "success" : true,
  "code" : 1
}
```


+ Request (application/json)
  {
      "info": {
          "empty": 7,
          "emptyTime": "20160906112022",
          "oneHour": 13.2,
          "oneTime": "2016090613022",
          "twoHour": 11.1,
          "twoTime": "2016090614022",
          "threeHour": 8.6,
          "threeTime": "2016090615022"
      },
      "itemType": 8,
      "orginId": 6,
      "profileId": 1910307,
      "staffId": 500023,
      "time": "20160906145243",
      "token": "158e47b4c98e46b295be01fbc6edefb9"
  }

+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 日常数据列表 [POST /enterprise/health/list]
查询日常数据列表

```js
{
    "orgId": 8888,//机构ID
    "size": 10,//查询数量
    "startId": 231123123,//开始查询的记录ID
    "startTime": "20160701111111",//开始查询的时间
    "token": "token",//token
    "type": 0,//获取最新数据(下拉刷新时)为0  获取下一页(下拉获取更多时)为1|
    "uid": 9999 //患者uid(profileId)
}
```

参数说明:
当type为 0 时,startId和startTime 可不传

返回结果

```json
{
    "code": 1,
    "data": {
        "items": [
            {
                 "id": 245,//数据ID
                "create": "20160701112035",//数据提交时间
                "info": '[{"name": "脑残片","type": 1},{"name": "秀逗丸","type": 2}]',//数据值
                "itemType": 2,//测量类型:1=血压 2=服药，3=体温4=体重5=心率6=身高7=血氧8=血糖9=呼吸率
                "orginId": 77777,//机构编号
                "profileId": 99999,//病患编号
                "staffId": 88888,//服务者编号
                "time": "20160629141212",//数据测量时间
                "type": 2//  计划类型,1自测血压计划  2,CBA计划
            },
            {
             "id": 245,
                "create": "20160701112030",
                "info": '{"sbp": 120,"dbp": 90,"pulse": 79}',  血压
                "itemType": 1,
                "orginId": 77777,
                "profileId": 99999,
                "staffId": 88888,
                "time": "20160629141212",
                "type": 2
            },
            {
                 "id": 245,
                "create": "20160701112026",
                "info": '{"hr": 90}',   //心率
                "itemType": 5,
                "orginId": 77777,
                "profileId": 99999,
                "staffId": 88888,
                "time": "20160629141212",
                "type": 2
            },
            {
             "id": 245,
                "create": "20160701112019",
                "info": '{"bw": 65.9}',
                "itemType": 4,
                "orginId": 77777,
                "profileId": 99999,
                "staffId": 88888,
                "time": "20160629141212",
                "type": 2
            },
            {
                "id": 245,
                "create": "20160701112010",
                "info": '{"bt": 65.9}',
                "itemType": 3,
                "orginId": 77777,
                "profileId": 99999,
                "staffId": 88888,
                "time": "20160629141212",
                "type": 2
            },
            {
                 "addId": 500023,
                 "addUserType": 2,
                 "create": "20160906151854",
                 "id": 544,
                 "info": "
                         {\"empty\":7.0,  //空腹血糖
                        \"emptyTime\":\"201609061120221\",
                        \"oneHour\":13.2,  //1小时血糖
                        \"oneTime\":\"20160906130221\",
                        \"threeHour\":8.6,  //2小时血糖
                        \"threeTime\":\"20160906150221\",
                        \"twoHour\":11.1,   //3小时血糖
                        \"twoTime\":\"20160906140221\"
                         }",
                 "itemType": 8,
                 "orginId": 6,
                 "profileId": 1910307,
                 "time": "20160906145243",
                 "type": 2
             },
           {
                "addId": 500023,
                "addUserType": 2,
                "create": "20160906152103",
                "id": 546,
                "info": "{\"bloodOx\":172}",  //血氧
                "itemType": 7,
                "orginId": 6,
                "profileId": 1910307,
                "time": "20160906145243",
                "type": 2
            },
           {
                "addId": 500023,
                "addUserType": 2,
                "create": "20160906152020",
                "id": 545,
                "info": "{\"beath\":20}",  //呼吸率
                "itemType": 9,
                "orginId": 6,
                "profileId": 1910307,
                "time": "20160906145243",
                "type": 2
          },
          {
                "addId": 500023,
                "addUserType": 2,
                "create": "20160906144707",
                "id": 540,
                "info": "{\"height\":172}",  //身高
                "itemType": 6,
                "orginId": 6,
                "profileId": 1910307,
                "time": "20160906144143",
                "type": 2
          }
        ]
    },
    "success": true
}
```


+ Request (application/json)
  {
      "orgId": 6,
      "size": 10,
      "startId": 0,
      "startTime": "20160906151412",
      "token": "764ec54c620446638b286044361ea466",
      "type": 0,
      "uid": 1910307
  }

+ Response 200 (application/json)
{
  "code": 1,
  "data": {
    "items": [
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160918112644",
        "id": 631,
        "info": "{\"empty\":7,\"emptyTime\":\"20160906112022\",\"oneHour\":13.2,\"oneTime\":\"20160906130202\",\"threeHour\":8.6,\"threeTime\":\"20160906150202\",\"twoHour\":11.1,\"twoTime\":\"20160906140202\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160908181811",
        "id": 593,
        "info": "{\"empty\":7,\"emptyTime\":\"20160906112022\",\"oneHour\":13.2,\"oneTime\":\"20160906130202\",\"threeHour\":8.6,\"threeTime\":\"20160906150202\",\"twoHour\":11.1,\"twoTime\":\"20160906140202\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160907180653",
        "id": 564,
        "info": "{\"empty\":7,\"emptyTime\":\"201609061120221\",\"oneHour\":0,\"oneTime\":\"\",\"threeHour\":0,\"threeTime\":\"\",\"twoHour\":0,\"twoTime\":\"\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160907180626",
        "id": 563,
        "info": "{\"empty\":7,\"emptyTime\":\"201609061120221\",\"oneHour\":13.2,\"oneTime\":\"\",\"threeHour\":8.6,\"threeTime\":\"\",\"twoHour\":11.1,\"twoTime\":\"\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160907180615",
        "id": 562,
        "info": "{\"empty\":7,\"emptyTime\":\"201609061120221\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160906152103",
        "id": 546,
        "info": "{\"bloodOx\":172}",
        "itemType": 7,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160906152020",
        "id": 545,
        "info": "{\"beath\":20}",
        "itemType": 9,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160906151854",
        "id": 544,
        "info": "{\"empty\":7,\"emptyTime\":\"201609061120221\",\"oneHour\":13.2,\"oneTime\":\"20160906130221\",\"threeHour\":8.6,\"threeTime\":\"20160906150221\",\"twoHour\":11.1,\"twoTime\":\"20160906140221\"}",
        "itemType": 8,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160906150806",
        "id": 543,
        "info": "{}",
        "itemType": 7,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      },
      {
        "addId": 500023,
        "addUserType": 2,
        "create": "20160906150420",
        "id": 542,
        "info": "{}",
        "itemType": 7,
        "orginId": 6,
        "profileId": 1910307,
        "time": "20160906145243",
        "type": 2
      }
    ]
  },
  "success": true
}

# 用户反馈 [POST /user/feedback]

用户反馈
请求参数
```json
{
    "token": "",
    "feedback": "反馈",
    "contact":""//联系方式,
    "target":"反馈针对的平台or项目"//郑大一项目此处值为: cba
}
```
返回结果

+ Request (application/json)
  {
      "token": "cfb30ea7324f4e2bb872934b00b19ab6",
      "feedback": "反馈",
      "contact":"15210607693",
      "target":"cba"
  }
+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {}
  }


# 获取诊断报告地址 [GET /enterprise/diagnosis/url/{token}/{companyId}]

根据服务者token获取诊断报告地址


请求字段说明：
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|Y|帐号token|
|companyId|int|Y|帐号名称|

+ Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
      + companyId:6(required,String) - 当前accountId下的profileId
+ Request (application/json)

+ Response 200 (application/json)
{
 "code": 1,
 "data": {
    "download": "http://hmp.dev.cim120.cn/user/diagnose/healthguidance/pdf/download?taskId=",
    "export": "http://hmp.dev.cim120.cn/user/diagnose/healthguidance/pdf/export?taskId="
 },
 "success": true
}