>postman数据：https://www.getpostman.com/collections/710ba5fdffa62d78411b

# 发送验证码 [POST /users/code]

功能：客户端用户注册或重置密码时发送验证码

|名称|类型|是否必需|说明|
|----|----|----|----|
|phone|int|Y|用户手机号|
|type|String|Y|消息类型，register/reset/bind/resetphone/bind_contact|
|send|int|N|默认1发送短信，0不发短信，仅内网测试使用|

+ Request (application/x-www-form-urlencoded)
    phone=15210607694&type=register&send=0
+ Response 200 (application/json)
    {
      "code": 1,
      "data": {
        "code": "5012"
      },
      "success": true
    }

# 验证验证码 [POST /users/checkCode]

客户端校验用户输入的短信验证码

|名称|类型|是否必需|说明|
|----|----|----|----|
|phone|int|Y|用户手机号|
|code|int|Y|短信验证码|
|type|String|Y|消息类型，register/reset|

+ Request (application/x-www-form-urlencoded)
  phone=15210607694&code=2270&type=register
+ Response 200 (application/json)
    {
        "success": true,
        "code": 1,
        "data": {}
    }


# 用户注册 [POST /user/register]

客户端调用接口进行用户注册，返回新token及用户id

|名称|类型|是否必需|说明|
|----|----|----|----|
|phone|int|Y|手机号|
|password|String|Y|密码|
|imei|String|Y|手机imei号|
|type|int|Y|客户端类型，0安卓，1ios|
|code|int|Y|短信验证码|
|platform|int|Y|默认参数mobile|

+ Request (application/json)
    {
        "phone": "15210607694",
        "password": "register",
        "pushId":"111112222"
    }

+ Response 200 (application/json)
    {
        "success":true,
        "code":1,
        "data":{
            "token":"588574e36410eac22170b167e5cef2c3",
            "uid":50012
        }
    }

# 用户登录 [POST /user/login]

客户端调用接口进行用户登录，返回新token及用户基本信息

  |名称|类型|是否必需|说明|
  |----|----|----|----|
  |phone|int|Y|用户手机号|
  |password|String|Y|密码|
  |imei|String|Y|设备imei号|
  |type|int|Y|设备类型，0:安卓;1:ios|
  |platform|String|Y|默认mobile|

+ Request (application/json)
  {
    "phone": "15210607694",
    "password": "register"
  }

+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {
          "token":"588574e36410eac22170b167e5cef2c3",
          "uid":123,
          "name":"张三"
      }
  }

# 重置密码 [POST /users/resetPassword]

重置密码

|名称|类型|是否必需|说明|
|----|----|----|----|
|phone|int|Y|用户手机号|
|code|int|Y|短信验证码|
|password|String|Y|新密码|

+ Request (application/x-www-form-urlencoded)
  phone=15210607693&code=1357&password=123456

+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {}
  }

# 修改用户资料 [POST /user/edit]

客户端用户修改本人基本信息

|名称|类型|是否必需|说明|
|----|----|----|----|
|phone|int|Y|用户手机号|
|code|int|Y|短信验证码|
|password|String|Y|新密码|

+ Request (application/json)
  {
      "token":"cfb30ea7324f4e2bb872934b00b19ab6",
      "nickname":"yxiao"
  }
+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {
          "data": {
              "name":""
          }
      }
  }

# 用户反馈 [POST /user/feedback]

用户反馈

+ Request (application/json)
  {
      "token": "cfb30ea7324f4e2bb872934b00b19ab6",
      "feedback": "反馈",
      "contact":"15210607693"
  }
+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {}
  }
