FORMAT: 1A
HOST: http://mock.dev.cim120.cn

# kinton接口文档

# 项目介绍

本项目用于CIM所有客户端的HTTP API服务。文档以模块分组，以便以查看。

- devlop地址：http://kinton.dev.cimyun.com
- qa地址：http://kinton.qa.cimyun.com

推荐使用chrome插件[postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop),进行HTTP请求调试

# Group 状态码
<!-- include(code.md) -->

# Group 首页与配置
<!-- include(kinton-home.apib) -->

# Group Account相关
<!-- include(kinton-account.apib) -->

# Group Profile相关
<!-- include(kinton-profile.apib) -->

# Group Profile健康相关
<!-- include(kinton_health.apib) -->

# Group Account与Profile关联
<!-- include(kinton-accProRelate.apib) -->

# Group device设备数据
<!-- include(kinton_device.apib) -->

# Group CBA数据字典
<!-- include(cba_dictionary.md) -->

# Group CBA相关
<!-- include(kinton-cba.apib) -->
