>postman数据：https://www.getpostman.com/collections/51ab875c6e760683c7d8

# 健康报告详情 [GET /health/report/detail/{token}/{profileId}/{type}]

功能：客户端取用户的健康详细报告

params :
|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|Y|用户token|
|profileId|Long|Y|用户profileID|
|type|String|Y|报告类型，1日，2周，3月|

+ Parameters
 + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
 + profileId:1910300 (required,int) - 用户登录后的token
 + type:1 (required,int) - 用户登录后的token

+ Response 200 (application/json)

{
    "code": 1,
    "data": {
        "detail": {
            "dateInterval": "2016年5月8日",
            "detail": "【今日血压报告】2016-5-4,平均血压为131/90；非规定时间131/90；血压正常范围为 100 - 120 / 60 - 80。\n# 最近还没有测定早晨血压。请注意：早晨（6 - 10点）血压升高很常见，所以需要特别关注，我国清晨血压临床管理的中国专家指导建议经常测量早晨血压。\n# 高压（SBP）在血压在边缘升高范围小范围波动，巨大幅度波动。平均 131mmHg高于血压正常范围的上限,对心脑血管有损害； \n# 低压（DBP）平均 90mmHg远高于血压正常范围的上限，进入高血压范围（诊断待定）。低压是在正常（很低）到1级高血压水平间，巨大幅度波动。\n# 今日血压监测结果要点：血压高，1级高血压水平。",
            "sumDays": 17,
            "summary": "今日血压监测结果要点：血压高，1级高血压水平。"
        }
    },
    "success": true
}

# 健康报告 [GET /health/report/{token}/{profileId}/{type}]

 功能：客户端取用户的健康详细报告

 params :
 |名称|类型|是否必需|说明|
 |----|----|----|----|
 |token|String|Y|用户token|
 |profileId|Long|Y|用户profileID|
 |type|String|Y|报告类型，1日，2周，3月|

 `Response`返回的数据：

 ```js
 {
     "success" : true,
     "code"    : 1,
     "data"    : {
         "report" : {
           "sbp"    :  130，
           "sbpDev"  :  10,//高压偏差，正为大于当前值，负为小于当前值
           "dbp"    :  75,
           "dbpDev"  :  -10,//低压偏差
           "time"    :  "3月8日-3月14日",//时间
           "sumDays"  :  5,
           "sumTimes"  :  13,
           "summary"    :  "平均血压高，为2级高血压水平",
           "notice"  :  "需要尽快就医，以明确血压长高问题，以及治疗方案"
         },
         "bps":[
           {
             "day"    :  "3月14日",
             "sbpAvg"  :  120,//高压平均
             "dbpAvg"  :  90,//低压平均
             "list"    :  [
               {
                 "sbp"      :  120,
                 "dbp"      :  90,
                 "time"  :  20160314140000//yyyyMMddHHmmss
               },
               ...
             ]
           },
           ...
         ]
     }
 }

 ```

 + Parameters
  + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
  + profileId:1910300 (required,int) - profileId
  + type:1 (required,int) - 报告类型

 + Response 200 (application/json)

 {
   "code": 1,
   "data": {
     "bps": [
       {
         "day": "09月19日",
         "dbpAvg": 80,
         "list": [
           {
             "dbp": 80,
             "sbp": 120,
             "time": "20160919115500"
           }
         ],
         "sbpAvg": 120
       }
     ],
     "report": {
       "dbp": 79,
       "dbpDev": -1,
       "notice": "需要观察，生活方式干预。\n\n",
       "sbp": 120,
       "sbpDev": 0,
       "sumDays": 1,
       "sumTimes": 1,
       "summary": "今日血压监测结果要点：血压边缘升高状态。",
       "time": "(2016-09-19)"
     }
   },
   "success": true
 }

# 添加药物 [POST /health/medicine]

 客户端保存用户添加的药物
 type计划类型：
 | ID | 说明 |
 | -- | -- |
 | 1 | 血压 |

 medicineType药物类型：
 | ID | 说明 |
 | -- | -- |
 | 0 | 普利 |
 | 1 | 沙坦 |
 | 2 | β阻 |
 | 3 | Ca拮 |
 | 4 | 利尿 |
 | 5 | 其他 |

 + Request (application/json)
{
    "token"    :    "6508b0df496d4fe798706d44c3a734e7",
    "profileId" : 1910300,
    "medicine"    :  {
        "type"           :   1,
        "medicineType"   :   0,
        "name"           :   "拜新同"
    }
}

 + Response 200 (application/json)

  {
    "code": 1,
    "data": {
      "name": "拜新同",
      "id": 130
    },
    "success": true
  }

# 添加服药记录 [POST /health/medicine/record]

 客户端保存用户添加的药物


 + Request (application/json)
{
    "token": "08b7259fa048427796e76c6f39c1c5d7",
    "profileId": 1910300,
    "time": "114425",
    "medicines": [
        {
            "medicineId": 1,
            "dose": 300
        },
        {
            "medicineId": 2,
            "dose": 300
        }
    ]
}

 + Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 药物查询 [GET /health/medicine/{token}/{profileId}]

 功能：客户端取用户的健康详细报告

 params :
 |名称|类型|是否必需|说明|
 |----|----|----|----|
 |token|String|Y|用户token|
 |profileId|Long|Y|用户profileID|


 type计划类型：
 | ID | 说明 |
 | -- | -- |
 | 1 | 血压 |

 medicineType药物类型：
 | ID | 说明 |
 | -- | -- |
 | 0 | 普利 |
 | 1 | 沙坦 |
 | 2 | β阻 |
 | 3 | Ca拮 |
 | 4 | 利尿 |
 | 5 | 其他 |



 + Parameters
  + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
  + profileId:1910300 (required,int)


 + Response 200 (application/json)

 {
   "code": 1,
   "data": {
     "datas": [
       {
         "id": 130,
         "medicineType": 0,
         "name": "拜新同",
         "type": 1
       }
     ]
   },
   "success": true
 }


# 药物删除 [DELETE /health/medicine/{token}/{profileId}/{medicineId}]

  功能：客户端取用户的健康详细报告

  params :
  |名称|类型|是否必需|说明|
  |----|----|----|----|
  |token|String|Y|用户token|
  |profileId|Long|Y|用户profileID|
  |medicineId|Long|Y|药物ID|

  + Parameters
   + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
   + profileId:1910300 (required,int)
   + medicineId:130 (required,int)


  + Response 200 (application/json)

  {
    "code": 1,
    "data": {
      "datas": [
        {
          "id": 130,
          "medicineType": 0,
          "name": "拜新同",
          "type": 1
        }
      ]
    },
    "success": true
  }

# 健康计划开启 [POST /health/notice]

客户通知服务端用户开启健康计划

返回的数据：

```js
{
  "success" : true,
  "code" : 1,
  "data" : {
        "err":"如果创建失败.code为7008,此处字段为具体的错误信息,如:年龄太小哟~",
        "patientId": "35c0e717136f434abef096c8ecd66ce8",
        "joinTime": "20160503143715"
  }
}

```

 + Request (application/json)
{
    "token"    :"f8c7493d1c1544bfad64e7a89166b080",
    "profileId" :1910300,
    "time"    :    "20160919140000"
}

 + Response 200 (application/json)

  {
    "code": 1,
    "data": {
      "patientId": "2eb6a43478ca46b58be0ee40a299f6cc",
      "joinTime": "20160919144125"
    },
    "success": true
  }

# 健康首页 [POST /health/home]

  健康首页

+ Request (application/json)
  {
     "token"     :   "2cf1ee80dbf7405bbd5f413fc21174d0",
     "profileId" : 1903824,
    "pageSize"  :   10,
    "pageNum"  :  1
  }

+ Response 200 (application/json)

{

    "code": 1,
      "data": {
        "total": 2,
        "data": [
          {
            "info": "{\"dbp\":80,\"msg\":\"血压正常\",\"sbp\":120}",
            "itemType": 1,
            "time": "20160913111100",
            "type": 1
          },
          {
            "info": "{\"dbp\":80,\"msg\":\"血压正常\",\"sbp\":120}",
            "itemType": 1,
            "time": "20160913111000",
            "type": 1
          }
        ],
        "pageSize": 10,
        "pageNum": 1,
        "totalBp": 2
      },
      "success": true
}
