# 设备数据上传接口 [POST /device/upload]

设备数据上传接口
od : post
params :
|名称|类型|是否必需|说明|
|----|----|----|----|
|data|byte[]|Y|设备数据msgPack格式byte数组|

文件格式说明：
|名称|类型|说明|
|----|----|----|
|token|String|用户token|
|profileId|Long|用户profile|
|platform|String|手机平台|
|count|int array|数据数量数组：0头戴数,1血压数,2儿童手环体温数,3设备数,4儿童手环干预数据|
|headsetData|float array|头戴数据数据|
|bloodPressureData|float array|血压数据数据|
|childBandData|float array|儿童手环测量数据|
|deviceData|String array|设备信息数据|
|childBandTreatmentData|float array|儿童手环干预数据|

headsetData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2-33|float|测量数据|

bloodPressureData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|sbp|
|3|float|dbp|
|4|float|pulse|
|5|int|inputType,1设备测量录入,2手动录入|

childBandData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|体核温度|
|3|float|目标温度|
|4|float|环境温度|

deviceData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|String|时间串，格式yyyyMMddHHmmss|
|1|String|action:-1默认,0绑定,1解绑|
|2|String|type|
|3|String|bluetooth|
|4|String|name|
|5|String|version|
|6|String|hardwareType|
|7|String|markettypeName|

childBandTreatmentData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|type:1物理,2药物|



返回字段说明：

|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|[[状态码]]|
|data|Object|返回结果数据|

返回格式json:

```json
{
  "success" : true,
  "code" : 1,
  "data" : {}
}

```

+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {}
  }


# 设备离线数据上传接口 [POST /device/asyncUpload]

设备离线数据上传接口
method : post
params :
|名称|类型|是否必需|说明|
|----|----|----|----|
|data|byte[]|Y|设备数据msgPack格式byte数组|

文件格式说明：
|名称|类型|说明|
|----|----|----|
|token|String|用户token|
|profileId|Long|用户profile|
|platform|String|手机平台|
|count|int array|数据数量数组：0头戴数,1血压数,2儿童手环体温数,3设备数,4儿童手环干预数据|
|headsetData|float array|头戴数据数据|
|bloodPressureData|float array|血压数据数据|
|childBandData|float array|儿童手环测量数据|
|deviceData|String array|设备信息数据|
|childBandTreatmentData|float array|儿童手环干预数据|

headsetData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2-33|float|测量数据|

bloodPressureData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|sbp|
|3|float|dbp|
|4|float|pulse|
|5|int|inputType,1设备测量录入,2手动录入|

childBandData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|体核温度|
|3|float|目标温度|
|4|float|环境温度|

deviceData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|String|时间串，格式yyyyMMddHHmmss|
|1|String|action:-1默认,0绑定,1解绑|
|2|String|type|
|3|String|bluetooth|
|4|String|name|
|5|String|version|
|6|String|hardwareType|
|7|String|markettypeName|

childBandTreatmentData格式说明：
|顺序|类型|说明|
|----|----|----|
|0|float|时间数值，格式yyyyMMddHHmmss前7位|
|1|float|时间数值，格式yyyyMMddHHmmss后7位|
|2|float|type:1物理,2药物|



返回字段说明：

|名称|类型|说明|
|----|----|----|
|success|boolean|处理结果,成功true, 失败false|
|code|int|[[状态码]]|
|data|Object|返回结果数据|

返回格式json:

```json
{
  "success" : true,
  "code" : 1,
  "data" : {}
}

```

+ Response 200 (application/json)
  {
      "success": true,
      "code": 1,
      "data": {}
  }


# 固件版本检查 [GET /device/update/check/{deviceType}/{version}]

固件版本检查，当服务端取的版本号提交的版本要大，返回新的版本号和下载url;否则data为空


+ Parameters
  + deviceType:ChildBand (required,String) - 用户登录后的token
  + version:103(required,String) - 当前accountId下的profileId

+ Response 200 (application/json)

{
  "code": 1,
  "data": {
    "version": 131,
    "url": "http://files-test.cim120.cn/om/ota/20160912/cim_tw_v2110_131_zyh_20160907.zip",
    "desc": "131"
  },
  "success": true
}


# 设备绑定历史 [POST /device/history]

根据token 那到accountId得到当前账户下绑定的设备

+ Parameters
      + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token

+ Response 200 (application/json)
{
  "code": 1,
  "data": {
    "datas": [
      {
        "bluetooth": "E5:EC:8B:E8:33:C7",
        "createTime": "20160918151859",
        "hardwareType": "default",
        "markettypeName": "default",
        "name": "CIM-TW1-33C7",
        "type": 3,
        "uid": 1910188,
        "version": "132"
      }
    ]
  },
  "success": true
}

# 设置设备预警阀值 [POST /device/set]

根据token 那到accountId得到当前账户下绑定的设备

参数
```json
{
    "profileId":1910300,   //profileId
    "teniaSet":    //头戴设备
        {
        "heartHigh":195,    //心率高
        "heartLow":40,      //心率低
        "raHigh":40,        //呼吸率高
        "raLow":12,         //呼吸率低
        "spo2Low":90,        //血氧含量
        "tempHigh":39.5,    //温度高
        "tempLow":35.5       //温度低
        },
    "token":"75cc57dff92d4320aef097344998306d",
    "wristStrapSet":   //儿童手环
        {
        "ms":120,    //测量间隔时间
        "offScreen":60,//自动熄屏时间
        "warningHighTemp":39.5,//高温预警
        "warningLowTemp":35.5,//低温预警
        "remind": false  //true 开启false 关闭
        }

}
```
返回结果：

```json
{
  "code": 1,
  "data": {},
  "success": true
}
```

+ Request (application/json)
{
    "profileId": 1910188,
    "teniaSet": {
        "heartHigh": 195,
        "heartLow": 40,
        "raHigh": 40,
        "raLow": 12,
        "spo2Low": 90,
        "tempHigh": 39.5,
        "tempLow": 35.5
    },
    "token": "94589a0409d2446999e136c2120a9f95",
    "wristStrapSet": {
        "ms": 120,
        "offScreen": 60,
        "warningHighTemp": 39.5,
        "warningLowTemp": 35.5,
        "remind": false
    }
}

+ Response 200 (application/json)
{
  "code": 1,
  "data": {},
  "success": true
}

# 血压查询接口 [POST /bp/data]

血压查询接口

参数不对时：返回结果中code：0 ，sucsess：false

参数说明：

|名称|类型|是否必需|说明|
|----|----|----|----|
|token|String|APP必须有/PC不需要|用户登录token|
|uid|Long|N/PC接口Y|用户uid|
|pageSize|Integer|Y|每页条数|
|time|String|Y|起始数据的采集时间, 格式yyyyMMddHHmmss|
|type|Integer|Y|默认下一页0（返回小于采集时间的数据） 上一页1（返回大于采集时间的数据）|
|isReverse|Integer|N|结果集顺序开关，默认0，0正序，1反序|
返回结果：



+ Request (application/json)
{
  "token"       :   "00dff83a6c354aff83331781c29c4dad",
  "uid"         :   1903824,
  "time"        :   "20160919150321",
  "type"        :   1,
  "isReverse"   :   1
}

+ Response 200 (application/json)
{
    "code": 1,
    "data": {
        "datas": [
            {
                "datas": [
                    {
                        "dbp": 71,
                        "id": 200043,
                        "pulse": 79,
                        "sbp": 171,
                        "time": "20151128110300"
                    },
                    {
                        "dbp": 198,
                        "id": 200042,
                        "pulse": 59,
                        "sbp": 249,
                        "time": "20151128110800"
                    }
                ],
                "time": "20151128"
            },
            {
                "datas": [
                    {
                        "dbp": 80,
                        "id": 200024,
                        "pulse": 204,
                        "sbp": 121,
                        "time": "20151130120100"
                    },
                    {
                        "dbp": 78,
                        "id": 200023,
                        "pulse": 75,
                        "sbp": 106,
                        "time": "20151130140300"
                    }
                ],
                "time": "20151130"
            }
        ]
     "firstID":"20151128110300",
    "lastID":"20151130140300"
    },
    "success": true
}
# 儿童手环干预查询 [GET /childBand/treatment/{token}/{profileId}/{pageSize}/{pageNo}]

客户端取儿童手环的干预列表,按时间倒序返回结果

 params :
 |名称|类型|是否必需|说明|
 |----|----|----|----|
 |token|String|Y|用户token|
 |profileId|Long|Y|用户profileID|
 |pageSize|int|Y|分页大小|
 |pageNo|int|Y|当前页|



 + Parameters
  + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
  + profileId:1910300 (required,int) - profileId
  + pageSize:10 (required,int) - 报告类型
  + pageNo:1 (required,int) - 报告类型

 + Response 200 (application/json)

 {
   "success" : true,
   "code" : 1,
   "data" : {
     "pageSize"      :   20,
     "pageNo"        :   1,
     "totalItems"    :   100,
     "datas"  :   [
         {
             "id"    :   1,
             "type"  :   1,
             "time"  :   "20160217121000"
         },
         {
             "id"    :   2,
             "type"  :   2,
             "time"  :   "20160217110800"
         }
     ]
   }
 }

