>postman数据：https://www.getpostman.com/collections/e131465b93004a2e52be

# 保存profile [POST /profile/save]

客户端调用接口保存profile，profileId的0新增，否则修改

身份证重复的时候会返回重复的profileID
如：
{
  "code": 2005,
  "data": {
    "id": 1910377
  },
  "success": true
}
+ Request (application/json)
{
  "token": "75cc57dff92d4320aef097344998306d",
  "profileId": 0,
  "birthday": "2013-01-01",
  "name": "朵朵",
  "sex": 0,
  "iid": "421023198803160412",
  "weight": 76,
  "stature": 175,
  "face": ""
}

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
      "info": {
        "age": 3,
        "birthday": "2013-01-01",
        "face": "",
        "iid": "421023198803160412",
        "name": "朵朵",
        "profileId": 1902210,
        "sex": 0,
        "stature": 175,
        "token": "a8c46766665d41e6890a863f8a527320",
        "weight": 76.0,
        "warningHighTemp": 39.0,
        "warningLowTemp": 37.5,
        "ms": 20
      }
    },
    "success": true
  }

# account删除profile [POST /profile/remove/{token}/{profileId}]

解除account与profile的绑定

+ Parameters
    + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
    + profileId:1(required,number) - profileId
+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
    },
    "success": true
  }

# account绑定profile [POST /profile/add/{token}/{profileId}]

account与profile绑定

+ Parameters
    + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
    + profileId:1(required,number) - profileId
+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
    },
    "success": true
  }


# 查询profile列表 [GET /profile/list/{token}]

功能：查询profile列表，根据token获取accountId,获取accountId下的profile

返回参数说明：
```
"total":总条数,
"limit":可关联profile人数

"deviceSet":"设备高温及低温预警"
```
+ Parameters
 + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
      "total": 2,
      "limit": 3,
      "list": [{
        "accountId": 1910285,
        "age": 3,
        "birthday": "2013-01-01",
        "deviceSet": {
          "teniaSet": {
            "heartHigh": 220,
            "heartLow": 40,
            "raHigh": 40,
            "raLow": 12,
            "spo2Low": 90,
            "tempHigh": 39.5,
            "tempLow": 35
          },
          "wristStrapSet": {
            "ms": 120,
            "offScreen": 60,
            "remind": false,
            "warningHighTemp": 39.5,
            "warningLowTemp": 35.5
          }
        },
        "face": "",
        "iid": "",
        "ms": 15,
        "name": "朵朵",
        "profileId": 1910300,
        "sex": 0,
        "stature": 175,
        "warningHighTemp": 39,
        "warningLowTemp": 37.5,
        "weight": 76
      },
      {
        "accountId": 1910285,
        "age": 3,
        "birthday": "2013-01-01",
        "deviceSet": {
          "teniaSet": {
            "heartHigh": 195,
            "heartLow": 40,
            "raHigh": 40,
            "raLow": 12,
            "spo2Low": 90,
            "tempHigh": 39.5,
            "tempLow": 35.5
          },
          "wristStrapSet": {
            "ms": 120,
            "offScreen": 60,
            "remind": true,
            "warningHighTemp": 39.5,
            "warningLowTemp": 35.5
          }
        },
        "face": "",
        "iid": "421023198803160412",
        "name": "朵朵",
        "profileId": 1910285,
        "sex": 0,
        "stature": 175,
        "weight": 76
      }]
    },
    "success": true
  }


# 查询profile详情 [GET /profile/detail/{token}/{profileId}]

功能：根据profileId查询profile详情

返回参数说明：
```
"age":"年龄是根据365天计算的"

"deviceSet":"设备高温及低温预警"

```
+ Parameters
    + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
    + profileId:1910300(required,String) - 当前accountId下的profileId

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
      "info": {
        "accountId": 1910285,
        "age": 3,
        "birthday": "2013-01-01",
        "deviceSet": {
          "teniaSet": {
            "heartHigh": 220,
            "heartLow": 40,
            "raHigh": 40,
            "raLow": 12,
            "spo2Low": 90,
            "tempHigh": 39.5,
            "tempLow": 35
          },
          "wristStrapSet": {
            "ms": 120,
            "offScreen": 60,
            "remind": false,
            "warningHighTemp": 39.5,
            "warningLowTemp": 35.5
          }
        },
        "face": "http://fimg.cimyun.com/images/wap/default_img.jpg",
        "iid": "",
        "ms": 15,
        "name": "朵朵",
        "profileId": 1910300,
        "sex": 0,
        "stature": 175,
        "warningHighTemp": 39,
        "warningLowTemp": 37.5,
        "weight": 76
      }
    },
    "success": true
  }

# 获取profile健康信息 [GET /health/info/{token}/{profileId}]

功能：根据profileId  获取profile健康信息

返回参数说明：
```
{
"success" : true,
"code" : 1,
   "data" : {
   "time": "2016-05-14 11:30",
   "health":{
        "chd": false,//是否冠心病
        "dm": true,//是否糖尿病
        "dsLip": true,//是否血脂异常
        "diseaseRecord":"222", //过往病史
        "heartDisease":"333", //心里病史
         "family": {
                "famliyHistory":"111", //家族病史
                "acs": true,//是否<55/65岁心梗
                "dm": false,//是否糖尿病
                "dsLip": true,//是否血脂异常
                "hbp": true,//是否高血压
                "stroke": false//是否卒中
              },
        "hbp": false,//是否高血压
        "measure": {
                "fpg": 100,//空腹血糖
                "hdlc": 10,//高密度脂蛋白
                "height": 170,//身高
                "ldlc": 10,////低密度脂蛋白
                "pulse": 90,//脉搏
                "tc": 10,//总胆固醇
                "tg": 10,//甘油三脂
                "weight": 70//体重
             },
        "related": {
                "drink": 1,//饮酒
                "smoke": true//是否抽烟
         },
        "stroke": true,//卒中
        "strokeData": {
                "tia": false//TIA
        }
        }
   }
}

```
+ Parameters
  + token:5a7c78beda434f49bc8e80a00da0dbe2 (required,String) - 用户登录后的token
  + profileId:1910300(required,String) - 当前accountId下的profileId

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
      "health": {
        "chd": false,
        "diseaseRecord": "222",
        "dm": true,
        "dsLip": true,
        "family": {
          "acs": true,
          "dm": false,
          "dsLip": true,
          "famliyHistory": "111",
          "hbp": true,
          "stroke": false
        },
        "hbp": false,
        "heartDisease": "333",
        "measure": {
          "fpg": 100,
          "hdlc": 10,
          "height": 170,
          "ldlc": 10,
          "pulse": 90,
          "tc": 10,
          "tg": 10,
          "weight": 70
        },
        "related": {
          "drink": 1,
          "smoke": true
        },
        "stroke": true,
        "strokeData": {
          "tia": false
        }
      },
      "time": "2016-09-12 14:32"
    },
    "success": true
  }

# 编辑profile健康信息 [POST /health/edit]

客户端调用接口保存profile，profileId的0新增，否则修改

输入参数解释
```
  {
       "token" : "c125315f4d8d4df99f3585b9751c1acc",
       "type" : 1, //更新模块,0 为更新个人健康信息模块, 1为更新家庭病信息
       "profileId":1910189,   //profileId
       "health":{
           "chd": false,//是否冠心病
           "dm": true,//是否糖尿病
           "dsLip": true,//是否血脂异常
           "diseaseRecord":"222", //过往病史
           "heartDisease":"333", //心里病史
           "family": {
              "famliyHistory":"111", //家族病史
               "acs": true,//是否<55/65岁心梗
               "dm": false,//是否糖尿病
               "dsLip": true,//是否血脂异常
               "hbp": true,//是否高血压
               "stroke": false//是否卒中
            },
           "hbp": false,//是否高血压
           "measure": {
               "fpg": 100,//空腹血糖
               "hdlc": 10,//高密度脂蛋白
               "height": 170,//身高
               "ldlc": 10,////低密度脂蛋白
               "pulse": 90,//脉搏
               "tc": 10,//总胆固醇
               "tg": 10,//甘油三脂
               "weight": 70，//体重
            },
            "related": {
                 "drink": 1,//饮酒
                "smoke": true//是否抽烟
            },
            "stroke": true,//卒中
            "strokeData": {
                "tia": false//TIA
            }
       }
  }
```

+ Request (application/json)
  {
    "token": "c125315f4d8d4df99f3585b9751c1acc",
    "type": 1,
    "profileId": 1910276,
    "health": {
      "chd": false,
      "dm": true,
      "dsLip": true,
      "diseaseRecord": "222",
      "heartDisease": "333",
      "family": {
        "famliyHistory": "111",
        "acs": true,
        "dm": false,
        "dsLip": true,
        "hbp": true,
        "stroke": false
      },
      "hbp": false,
      "measure": {
        "fpg": 100,
        "hdlc": 10,
        "height": 170,
        "ldlc": 10,
        "pulse": 90,
        "tc": 10,
        "tg": 10,
        "weight": 70
      },
      "related": {
        "drink": 1,
        "smoke": true
      },
      "stroke": true,
      "strokeData": {
        "tia": false
      }
    }
  }

+ Response 200 (application/json)
  {
    "code": 1,
    "data": {
    },
    "success": true
  }
